In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2024-08-21 11:09:57.858601: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
corpus = ['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
corpus

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define vocabulary size
voc_size = 10000

#one hot represenation for every word
one_hot_repsen = [one_hot(words,voc_size) for words in corpus]
one_hot_repsen


[[2849, 1996, 7542, 6782],
 [2849, 1996, 7542, 1412],
 [2849, 9663, 7542, 4913],
 [5500, 4434, 3081, 9398, 3402],
 [5500, 4434, 3081, 9398, 6378],
 [5323, 2849, 7399, 7542, 8417],
 [5019, 1977, 2022, 9398]]

In [5]:
# word embedding represetation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repsen,padding='pre', maxlen=sent_length)
embedded_docs

array([[   0,    0,    0,    0, 2849, 1996, 7542, 6782],
       [   0,    0,    0,    0, 2849, 1996, 7542, 1412],
       [   0,    0,    0,    0, 2849, 9663, 7542, 4913],
       [   0,    0,    0, 5500, 4434, 3081, 9398, 3402],
       [   0,    0,    0, 5500, 4434, 3081, 9398, 6378],
       [   0,    0,    0, 5323, 2849, 7399, 7542, 8417],
       [   0,    0,    0,    0, 5019, 1977, 2022, 9398]], dtype=int32)

In [9]:
dim = 10 # max is 300 dimenstions
model=Sequential()
model.add(Embedding(voc_size,dim,input_shape=(sent_length,)))
model.compile('adam','mse')


/Users/narasimharaovaddi/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/embedding.py:81: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [10]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step


array([[[-0.03388937, -0.01803475,  0.03858287,  0.04288492,
          0.03026232, -0.00420581,  0.03985855,  0.04949775,
          0.0383942 ,  0.01978948],
        [-0.03388937, -0.01803475,  0.03858287,  0.04288492,
          0.03026232, -0.00420581,  0.03985855,  0.04949775,
          0.0383942 ,  0.01978948],
        [-0.03388937, -0.01803475,  0.03858287,  0.04288492,
          0.03026232, -0.00420581,  0.03985855,  0.04949775,
          0.0383942 ,  0.01978948],
        [-0.03388937, -0.01803475,  0.03858287,  0.04288492,
          0.03026232, -0.00420581,  0.03985855,  0.04949775,
          0.0383942 ,  0.01978948],
        [ 0.02726725,  0.03267882, -0.02003707,  0.02025248,
         -0.03235658,  0.00651802,  0.00171455, -0.02040126,
         -0.02552189, -0.04908615],
        [ 0.04780677,  0.04932709,  0.00601685,  0.03613336,
          0.04412719, -0.00953169,  0.03065005,  0.00558786,
          0.01190119,  0.02699934],
        [ 0.00529342,  0.00413511,  0.01201955, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 2849, 1996, 7542, 6782], dtype=int32)